name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: Publish to the NPM registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org/

      - name: Publish
        run: |
          yarn install --ignore-scripts
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
